### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by esokullu** [Azure-Samples/azure-cosmos-db-graph-php-getting-started#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> vi connect.php # edit with server settings
> composer install # all fine
> php connect.php

### Any log messages given by the failure
```
Welcome to Azure Cosmos DB + Gremlin on PHP!

Attempting to connect...
Caught exception: gremlin-php driver has thrown the following error : 
PHP Fatal error:  Uncaught Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : Could not write to socket in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:791
Stack trace:
#0 /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php(523): Brightzone\GremlinDriver\Connection->error('Could not write...', 500, true)
#1 /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php(657): Brightzone\GremlinDriver\Connection->close()
#2 [internal function]: Brightzone\GremlinDriver\Connection->__destruct()
#3 {main}
  thrown in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php on line 791

Fatal error: Uncaught Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : Could not write to socket in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php on line 791

Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : Could not write to socket in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php on line 791

Call Stack:
    0.6116     561480   1. Brightzone\GremlinDriver\Connection->__destruct() /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:0
    0.6116     561480   2. Brightzone\GremlinDriver\Connection->close() /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:657
    0.6117     561480   3. Brightzone\GremlinDriver\Connection->error() /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:523

GymGroupss-Mac-Pro:cosmosdb esokullu$ php connect.php 
Welcome to Azure Cosmos DB + Gremlin on PHP!

Attempting to connect...
PHP Notice:  Undefined offset: 1 in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php on line 215
PHP Stack trace:
PHP   1. {main}() /Users/esokullu/Code/test/cosmosdb/connect.php:0
PHP   2. Brightzone\GremlinDriver\Connection->open() /Users/esokullu/Code/test/cosmosdb/connect.php:112
PHP   3. Brightzone\GremlinDriver\Connection->makeHandshake() /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:155

Notice: Undefined offset: 1 in /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php on line 215

Call Stack:
    0.0004     373512   1. {main}() /Users/esokullu/Code/test/cosmosdb/connect.php:0
    0.0022     569056   2. Brightzone\GremlinDriver\Connection->open() /Users/esokullu/Code/test/cosmosdb/connect.php:112
    6.7692     570472   3. Brightzone\GremlinDriver\Connection->makeHandshake() /Users/esokullu/Code/test/cosmosdb/vendor/brightzone/gremlin-php/src/Connection.php:155

Successfully connected to the database

We will proceed to drop whatever graph is on your collection.. Press any key to continue

	Dropping entire graph.
	Query: g.V().drop()
Caught exception:  :  > 
```

### Expected/desired behavior
> N/A

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
MacOS Sierra

### Versions
> PHP 7.1.1

### Mention any other details that might be useful

Tried two things;
1. edit the file as instructed
2. edit the file with the SSL field disabled as follows:
```
'ssl' => [
      'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false
      ]
    ]
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ephraimlambarte** [comment]
This happens to me when i add edge between vertices

**Comment by esokullu** [comment]
aren't we supposed to add vertices between edges :)
